### ISSUE TITLE
Doesn't pass through the 'globals' config.

### ISSUE THREAD

**Issue by Fitzpasd** [facebook-atom/jest-electron-runner#23]
Variables set using the [globals config](https://jestjs.io/docs/en/configuration.html#globals-object) aren't available when using this runner.

Is there a different approach people should be using to enable this scenario?

_jest.config.js_

```
module.exports = {
    globals: {
        __DEV__: true
    },
    runner: "@jest-runner/electron",
    testEnvironment: "@jest-runner/electron/environment",
    ...
}
```

Works with standard runner, error when using this one: `ReferenceError: __DEV__ is not defined`

**Comment by boujeepossum** [comment]
looks like a bug. good catch! 
i'm pretty sure 
we need to do the same as jest does here:
https://github.com/facebook/jest/blob/master/packages/jest-environment-node/src/index.js#L48

and add it to electron environment here https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/src/Environment.js#L18

@Fitzpasd do you mind submitting a PR? :)

**Comment by Fitzpasd** [comment]
Sure, will work on it now.
