### ISSUE TITLE
electron dependencies version are "electron": "^2.0.8",

### ISSUE THREAD

**Issue by githoniel** [facebook-atom/jest-electron-runner#31]
I see your package

```json
"electron": "^2.0.8",
```

I'm using electron 4.0.X and this cause my project to install two version of electron.

can we just do like
```json
"electron": *,
```

**Comment by rajivshah3** [comment]
Maybe it should be added as a `peerDependency` instead?

**Comment by githoniel** [comment]
Yes, Maybe 
```
peerDependency: {
   "electron":  ">= 2.0.8"
}
```
