### ISSUE TITLE
Serial execution when running with watcher

### ISSUE THREAD

**Issue by hovsater** [facebook-atom/jest-electron-runner#44]
Is there any reason why tests are run in series (see https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/src/TestRunner.js#L121) when running with the `--watch` option? It's unbearably slow and I couldn't find any references or documentation to why this was made.

**Comment by boujeepossum** [comment]
@KevinSjoberg i think there used to be a race condition, and having more than one worker always resulted in sketchy failures. seems like it's not the case any more. i made it use more workers here https://github.com/facebook-atom/jest-electron-runner/pull/45

**Comment by hovsater** [comment]
@aaronabramov thanks a lot for the explanation. Appreciate the quick fix as well. 🎉 🙌
