### ISSUE TITLE
Spawns multiple processes when using --watch

### ISSUE THREAD

**Issue by JM-Mendez** [facebook-atom/jest-electron-runner#5]
Hi, first off thanks for this package. Solves many issues for me. 

I have one issue tho. When running using `--watch`, I get multiple electron processes on each change. I was able to solve it by running `cleanup` after all tests, and it doesn't seem to cause any other issues or run differently.

I just removed this conditional.
https://github.com/facebook-atom/jest-electron-runner/blob/c4d7786a55b86d0b1d63c224d82c7d55660a41de/packages/electron/src/TestRunner.js#L129

Not sure if I'm missing something, or if this even merits a pull request. But I'd be happy to contribute with whatever you suggest.

**Comment by JM-Mendez** [comment]
After further test runs I discovered that rather than close the whole process, it was better to call `jestWorkerRPCProcess.start()` within the conditional below. This has allowed me to reuse the process making tests after the first run faster.

https://github.com/facebook-atom/jest-electron-runner/blob/c4d7786a55b86d0b1d63c224d82c7d55660a41de/packages/electron/src/TestRunner.js#L62

**Comment by boujeepossum** [comment]
hey @JM-Mendez 
thanks for using the package :) 
it's definitely a bug! i was able to reproduce it locally as well.
let me check the code and i'll try to ship the fix soon!

**Comment by boujeepossum** [comment]
published `@jest-runner/electron@0.0.14` that fixes the issue!
