### ISSUE TITLE
Specifying a different version of Electron (i.e. Electron 3.0.6)

### ISSUE THREAD

**Issue by aguynamedben** [facebook-atom/jest-electron-runner#6]
Thanks for the time you took to make this helpful module public.

Is there an easy way to configure this module to use a different version of Electron? I just upgrade from Electron 2 to Electron 3 and my test broke. I use node-sqlite3, a native module that places a file at `node_modules/sqlite3/lib/binding/electron-v3.0-darwin-x64/node_sqlite3.node`. When my test run, they're running from the Electron 2 environment, so they go looking for the path `node_modules/sqlite3/lib/binding/electron-v2.0-darwin-x64/node_sqlite3.node`, which is no longer in my project.

I hacked the [Electron version in package.json](https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/package.json#L12) in my project's node_modules, but I'm wondering if there's a better way to configure this.

Thanks again.

**Comment by boujeepossum** [comment]
curretly i have it hardcoded in here
https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/src/TestRunner.js#L29

which is probably not the best way. but this value can come from anywhere. i'm not very familiar with how node resolves dependencies, but it can probably automatically pick up whatever version is in package.json of the project under test. would that work?

**Comment by aguynamedben** [comment]
Ahh, thanks. I'm using this alternative now and it seems to be working: https://github.com/facebook/jest/issues/3698#issuecomment-340767259 I had to remove jest-electron-runner before it worked. One test is stalling out, but I think it's on my side.

**Comment by aguynamedben** [comment]
Hmm actually that solution makes native dependencies load from their Node.js path (i.e. /Users/ben/code/tesla/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node), not the Electron path. So I see why this is useful.

**Comment by aguynamedben** [comment]
@aaronabramov I submitted a PR that improves this: https://github.com/facebook-atom/jest-electron-runner/pull/8 The root project's Electron is used if it can be found, otherwise jest-electron-runner's Electron will be used. With this change the tests in my project correctly locate the Electron 3.x builds of native modules (i.e. node_modules/sqlite3/lib/binding/electron-v3.0-darwin-x64/node_sqlite3.node) because the tests are being run with the same Electron environment as my project.

After reading [this](https://hk.saowen.com/a/ce9f3446eb03d3efd9aabd9acb50dbe1e03a3ca0a8b4097f34d106794632d81f) I decided that determining the root path was a tricky enough problem to justify using the [app-root-path](https://github.com/inxilpro/node-app-root-path) module. Let me know if you prefer another method resolve the root path.

**Comment by boujeepossum** [comment]
@aguynamedben you mention stalling as well. i see some of CircleCI jobs timing out, so i assume something is thrown somewhere at some point and not handled properly. If you have a repro case for it or know what's happening that would be appreciated :)

**Comment by boujeepossum** [comment]
`@jest-runner/electron@0.1.0` is published
