### ISSUE TITLE
Runner hangs with electron 9.0.0

### ISSUE THREAD

**Issue by alejandroclaro** [facebook-atom/jest-electron-runner#64]
The runner hangs when electron is updated to version 9.0.0

Jest: v26.0.1
ts-jest: v26.0.0
@jest-runner/electron: 3.0.0

**Comment by yy923683900** [comment]
I get the same problem with you. And I have solved . 
Maybe the problem is caused by jest , can this solve your problem?
https://github.com/facebook/jest/issues/5239#issuecomment-355867359

**Comment by alejandroclaro** [comment]
Looks like it is solved.
