### ISSUE TITLE
Test suit fails to run outputs undefined

### ISSUE THREAD

**Issue by ashish-tru** [facebook-atom/jest-electron-runner#76]
running the command yarn test inside the electron project shows this error. I am not able to conclude anything from the output.
![runnerErr](https://user-images.githubusercontent.com/72724677/97969463-16f87f80-1de6-11eb-8ad7-36706a21a97e.PNG)
This is the test file which is failing 
![firstTest](https://user-images.githubusercontent.com/72724677/97969524-31caf400-1de6-11eb-9771-f242ecc0ed12.PNG)

**Comment by arvinxx** [comment]
meet this too.

what's the problem？Have you solved this?
i'm using Typeorm and sqlite3

**Comment by ashishrawat0** [comment]
Hey actually i idid solve this a long time ago. I think the problem was that i was using the build file instead of the ts file in which i did the code
